### ISSUE TITLE
cpi throws NotEnoughMemoryResource

### ISSUE THREAD

**Issue by medvedzver** [cloudfoundry-incubator/bosh-photon-cpi-release#13]
Hi!
Not sure if it's cpi error, but I think it's a good place to start.

I've deployed bosh director with photon cpi on PhotonController. 
Targeted this bosh director.
Trying to deploy dummy release.

Here is release manifest:
```
name: dummy

director_uuid: 091ff364-e9d8-4fce-8e04-118b71596cc6

releases:
- name: dummy
  version: latest

instance_groups:
- name: dummy
  instances: 1
  resource_pool: small_z1
  stemcell: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  networks:
  - name: cf_private
  jobs:
  - name: dummy
    release: dummy

update:
  canaries: 1
  max_in_flight: 6
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
```

here is director cloud config
```
---
networks:
- name: cf_private
  type: manual
  subnets:
  - range: 192.168.218.0/24
    gateway: 192.168.218.1
    dns: [192.168.218.1]
    reserved: ["192.168.218.1 - 192.168.218.50"]
    static: ["192.168.218.100 - 192.168.218.105"]
    cloud_properties:
      network_id: 1a0f751154288a2237720

compilation:
  workers: 1
  network: cf_private
  reuse_compilation_vms: true
  cloud_properties:
    vm_flavor: cluster-other-vm
    disk_flavor: cluster-vm-disk

resource_pools:
- name: small_z1
  network: cf_private
  stemcell: { name: 'bosh-vsphere-esxi-ubuntu-trusty-go_agent', version: latest}
  cloud_properties:
    vm_flavor: cluster-other-vm
    disk_flavor: cluster-vm-disk
```

So, it looks like I don't have enough memory in my project.
Here is my `cluster-other-vm` flavor:
```
1a0f751154288894ee9ca  cluster-other-vm                           vm               vm 1 COUNT
                                                                                   vm.flavor.cluster-other-vm 1 COUNT
                                                                                   vm.cpu 1 COUNT
                                                                                   vm.memory 4 GB
                                                                                   vm.cost 1 COUNT
```

This is my cluster-vm-disk:
```
1a0f751154288895231a0  cluster-vm-disk                            ephemeral-disk   ephemeral-disk 1 COUNT
                                                                                   ephemeral-disk.flavor.cluster-vm-disk 1 COUNT
```

Currently I have 
5 VMs out of 50 VMs Limit
10 Disks out of 50 Disks Limit
5 vCPUs out of 50 vCPUs Limit
20.00 GB out of 50 GB Limit Memory
95.00 GB out of 250 GB Limit Storage

I've checked config/cpi.json and it points to correct project. 

So here is result of `bosh -d dummy deploy dummy.yml`
```
12:33:23 | Creating missing vms: dummy/b2c3d75b-5d2e-44f8-b8f2-72133b5dfc91 (0) (00:00:01)
            L Error: CPI error 'Bosh::Clouds::CloudError' with message 'photon: Task '1a0f7511542c042b8e990' is in error state: {@step=={"sequence"=>"0","state"=>"ERROR","errors"=>[photon: { HTTP status: '0', code: 'NotEnoughMemoryResource', message: '', data: 'map[]' }],"warnings"=>[photon: { HTTP status: '0', code: 'InvalidEntity', message: 'Specified boot disk capacityGb is not used', data: 'map[]' }],"operation"=>"RESERVE_RESOURCE","startedTime"=>"1480768404141","queuedTime"=>"1480768404121","endTime"=>"1480768404238","options"=>map[e3b1660b-74b6-4ff5-a50e-2f1df2af07b3:vm]}}' in 'create_vm' CPI method
```

Any thoughts on what's failing?

Thank you and happy holidays!
